import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata = {
  title: "Jns Premium Stay",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header /> {/* Εμφάνιση του Header σε κάθε σελίδα */}
        {children} {/* Εδώ εμφανίζονται οι σελίδες του Next.js */}
        <Footer />  {/* Εμφάνιση του Footer σε κάθε σελίδα */}
      </body>
    </html>
  );
}